POST http://localhost:7071/api/search HTTP/1.1
content-type: application/json

{
    "q":"White cat",
    "top":8,
    "skip":32,
    "filters":[
        {
            "field":"language_code",
            "value":"en-GB"
        }
    ]
}